// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using WebService.Cap7.Data;

#nullable disable

namespace WebService.Cap7.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebService.Cap7.Model.Alerta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ColetaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("PontoDeDescarteId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool>("Resolvido")
                        .HasColumnType("BOOLEAN");

                    b.HasKey("Id");

                    b.HasIndex("ColetaId");

                    b.HasIndex("PontoDeDescarteId");

                    b.ToTable("Alertas");
                });

            modelBuilder.Entity("WebService.Cap7.Model.Coleta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("PontoDeDescarteId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<double>("Quantidade")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<int>("ResiduoId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("PontoDeDescarteId");

                    b.HasIndex("ResiduoId");

                    b.ToTable("Coletas");
                });

            modelBuilder.Entity("WebService.Cap7.Model.PontoDeDescarte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CapacidadeMaximaKg")
                        .HasColumnType("BINARY_DOUBLE");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<double>("QuantidadeAtualKg")
                        .HasColumnType("BINARY_DOUBLE");

                    b.HasKey("Id");

                    b.ToTable("PontosDeDescarte");
                });

            modelBuilder.Entity("WebService.Cap7.Model.Residuo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataColeta")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<double>("Peso")
                        .HasColumnType("BINARY_DOUBLE");

                    b.HasKey("Id");

                    b.ToTable("Residuos");
                });

            modelBuilder.Entity("WebService.Cap7.Model.Alerta", b =>
                {
                    b.HasOne("WebService.Cap7.Model.Coleta", "Coleta")
                        .WithMany()
                        .HasForeignKey("ColetaId");

                    b.HasOne("WebService.Cap7.Model.PontoDeDescarte", "Ponto")
                        .WithMany()
                        .HasForeignKey("PontoDeDescarteId");

                    b.Navigation("Coleta");

                    b.Navigation("Ponto");
                });

            modelBuilder.Entity("WebService.Cap7.Model.Coleta", b =>
                {
                    b.HasOne("WebService.Cap7.Model.PontoDeDescarte", "Ponto")
                        .WithMany("Coletas")
                        .HasForeignKey("PontoDeDescarteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebService.Cap7.Model.Residuo", "Residuo")
                        .WithMany()
                        .HasForeignKey("ResiduoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ponto");

                    b.Navigation("Residuo");
                });

            modelBuilder.Entity("WebService.Cap7.Model.PontoDeDescarte", b =>
                {
                    b.Navigation("Coletas");
                });
#pragma warning restore 612, 618
        }
    }
}
